### PR TITLE
Align release process with scapegoat

### PR DESCRIPTION
**Pull request by Johnnei**
To simplify the release processes across repos, I propose to align sbt-scapegoat with scapegoat. With this change both are published based on tags through CI.
This should also help to get release process clearer and get releases for sbt-scapegoat going again.

### CODE REVIEW

**Comment by mccartney** [comment]
Just to give some context - and not to leave your question unanswered:

- as mentioned in some other tickets, I don't have permissions/credentials to release the sbt-scapegoat project
- if I had, I wouldn't mind that much
- but I am not a user of `sbt-scapegoat` as I hardly use `sbt`

I think the most promising way would be to encourage people like you or someone else and let them take over the maintenance of the project.

**Comment by mccartney** [comment]
Sure thing.

And to give you some context.
Yes. I think it makes sense to align the release processes.
Or at the very least to have an easy possibility to release a version of `sbt-scapegoat` based on some new release of `scapegoat` (i.e. an optional alignment).

**Comment by Johnnei** [comment]
> Or at the very least to have an easy possibility to release a version of `sbt-scapegoat` based on some new release of `scapegoat` (i.e. an optional alignment).

I'm not necessarily thinking to release both in tandem, but mostly aligning both to use sbt-ci-release and tag based releases for simplicity and clarity (so the way to release is the same, but cycles might differ).

I am planning to do some experimentation with the `scapegoatVersion` variable to default based on the Scala major version, to simplify the out of the box experience. With this, tandem releases might make more sense to keep the default recent.

> is this PR enough to release `sbt-scapegoat` or do we need @sksamuel to put his credentials as secrets in this repo?

Unless you have admin on scapegoat itself as well, I think we need Sam to put the Sonatype credentials and GPG pair as variables in GitHub Actions: https://github.com/scapegoat-scala/scapegoat/blob/master/.github/workflows/master-release.yml#L40
If you do have admin, then you could copy the variables into GitHub actions settings. I would like @sksamuel 's upvote on the MR before doing so though (unless you feel otherwise?).

One thing that I'm not fully certain about in the MR, is the overrides scapegoat ci does regarding the GPG key variables: https://github.com/scapegoat-scala/scapegoat/blob/master/.github/workflows/master-release.yml#L17
The current sbt-ci-release template doesn't include that part. I'm not sure whether this is a newer set up or whether there was a fight with GPG key setup in the past (I always have a few hours of ci variable "fun" when I need to rotate my keys).

**Comment by mccartney** [comment]
I do have admin (which I didn't remember :D), but I don't see the current values of the secrets. It seems like Github makes them write-only for humans.
image

**Comment by mccartney** [comment]
> One thing that I'm not fully certain about in the MR,

About that I have no meaning input. I only faintly recall that the PGP keys have always been a bit of a struggle with various build tools (Maven, etc.) and the behavior varied over time/versions of these.

**Comment by Johnnei** [comment]
> It seems like Github makes them write-only for humans.

Ha, seems GitHub built the mythical Write Only Memory. I'm mostly using GitLab CI so wasn't aware of this feature in Github Actions. Looks we'll need support from Sam to set up the variables then.

**Comment by Johnnei** [comment]
@sksamuel Any chance we could get your help here?

**Comment by Johnnei** [comment]
In case you missed/forgot the last pings: @sksamuel Could you help you configure the same credentials in the Action Secrets as scapegoat so we can start publishing the plugin again?

**Comment by sksamuel** [comment]
Yep sorry, what are we needing here. Just GPP keys to publish to com.sksamuel.scapegoat ?

**Comment by Johnnei** [comment]
> Yep sorry, what are we needing here. Just GPP keys to publish to com.sksamuel.scapegoat ?

Thanks! According to sbt-ci-release, it should be the PGP key (PGP_SECRET (base64 of private key) / PGP_PASSPHRASE) and the Sonatype credentials to ship it to Maven central (SONATYPE_USERNAME / SONATYPE_PASSWORD)

https://github.com/sbt/sbt-ci-release#secrets

**Comment by sksamuel** [comment]
Ok, added:

PGP_SECRET - base64 armored key for sam@sksamuel.com
PGP_PASSPHRASE
SONATYPE_USERNAME
SONATYPE_PASSWORD

**Comment by Johnnei** [comment]
Just did a dry run with a tag based on this MR: https://github.com/scapegoat-scala/sbt-scapegoat/actions/runs/4932935859/jobs/8816423773#step:4:31
Will diagnose a bit later whether the ci template is doing something wrong here or if the encoding is really malformed 🤔

**Comment by Johnnei** [comment]
@sksamuel I've added a small snippet to validate the input and I think you may have forgotten to apply the base64 encoding. When looking at the first 4 and last 4 characters they're all ---- which I think suggests that it's "just" the armor format. Could you apply base64 and configure the PGP_SECRET again?

ref: https://github.com/scapegoat-scala/sbt-scapegoat/actions/runs/4976011215/jobs/8903698254#step:4:18

**Comment by sksamuel** [comment]
I armored it, but I don't know how to export as base64. Do you know the command @Johnnei

**Comment by Johnnei** [comment]
> I armored it, but I don't know how to export as base64. Do you know the command @Johnnei

@sksamuel https://github.com/sbt/sbt-ci-release#secrets has a few samples:

> macOS
> gpg --armor --export-secret-keys $LONG_ID | base64 | pbcopy
> Ubuntu (assuming GNU base64)
> gpg --armor --export-secret-keys $LONG_ID | base64 -w0 | xclip
> Arch
> gpg --armor --export-secret-keys $LONG_ID | base64 | sed -z 's;\n;;g' | xclip -selection clipboard -i
> FreeBSD (assuming BSD base64)
> gpg --armor --export-secret-keys $LONG_ID | base64 | xclip
> Windows
> gpg --armor --export-secret-keys %LONG_ID% | openssl base64

Usually just piping it through `| base 64` works. The final new-line tends mess up automation which is probably why they suggest to use a command to send it to the clipboard.

**Comment by sksamuel** [comment]
Ok try now @Johnnei

**Comment by Johnnei** [comment]
> Ok try now @Johnnei

Thanks! The last attempt looks to have published succesfully https://github.com/scapegoat-scala/sbt-scapegoat/actions/runs/5020848340/jobs/9002684401
I'll check in a few hours on central to confirm it all went fine.

**Comment by sksamuel** [comment]
sweet

**Pull request merged**
