### PR TITLE
Support Scala 2.13.11 and 2.12.18 out of the box

### PR DESCRIPTION
**Pull request by lolgab**

### CODE REVIEW

**Comment by Johnnei** [comment]
Thanks for the contribution! I'll patch up the test expectations and publish a patch release in a few hours :)

**Comment by svavassori** [comment]
Hello @Johnnei,

I'm in the process of update a project to Scala 2.13 that is using your plugin (1.2.1) but unfortunately `sbt` is not able to find the version 2.13 and it finds only the one for 2.12.
I have also manually checked at the maven [repo](https://mvnrepository.com/artifact/com.sksamuel.scapegoat) but it shows only the 2.12

Am I missing something or is there a different maven repo to which I can fetch it?

**Comment by Johnnei** [comment]
@svavassori Hi, the sbt-scapegoat scala version is linked from sbt. For SBT 1.x it will always be Scala 2.12 (hence the plugin is only 2.12). You're probably having issues with the scapegoat compiler plugin itself. Could you share the error from sbt on what it misses? (And for good measure please include sbt version and your scala 2.13 version as well)

**Comment by svavassori** [comment]
Hello @Johnnei 

I'm using sbt 1.9.2 that is compatible with 2.13. It turned out that the problem was that I was declaring the scala version (2.13.10) in the root module, so outside module compilation was using 2.12. Declaring as `ThisBuild / scalaVersion := "2.13.10"` in `build.sbt` resolved the issue.

Unfortunately I discovered the project has some dependencies that are compatible only with 2.12, so I've to postpone the upgrade for the time being. :-|

I'm sorry for the noise and thanks for the quick response!

**Pull request merged**
